//
// Generated file, do not edit! Created by opp_msgtool 6.0 from GossipMessage.msg.
//

#ifndef __GOSSIPMESSAGE_M_H
#define __GOSSIPMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class GossipMessage;
/**
 * Class generated from <tt>GossipMessage.msg:1</tt> by opp_msgtool.
 * <pre>
 * message GossipMessage
 * {
 *     string text;
 *     int taskId;
 *     string timestamp;
 * }
 * </pre>
 */
class GossipMessage : public ::omnetpp::cMessage
{
  protected:
    omnetpp::opp_string text;
    int taskId = 0;
    omnetpp::opp_string timestamp;

  private:
    void copy(const GossipMessage& other);

  protected:
    bool operator==(const GossipMessage&) = delete;

  public:
    GossipMessage(const char *name=nullptr, short kind=0);
    GossipMessage(const GossipMessage& other);
    virtual ~GossipMessage();
    GossipMessage& operator=(const GossipMessage& other);
    virtual GossipMessage *dup() const override {return new GossipMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getText() const;
    virtual void setText(const char * text);

    virtual int getTaskId() const;
    virtual void setTaskId(int taskId);

    virtual const char * getTimestamp() const;
    virtual void setTimestamp(const char * timestamp);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const GossipMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, GossipMessage& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline GossipMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<GossipMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __GOSSIPMESSAGE_M_H

